Import("env")


def source(file):
    return "#/src/" + file

env["source_files"] += [
    source("main.cpp"),
    source("app.cpp"),
    source("game.cpp")
]


# imgui module
SConscript("#src/imgui/SConscript", exports="env")